class ProductModel {
  String codArt;
  String desArtf;
  String grpArt;
  double prices;
  String codUniPrice;
  String codUni;
  String uniCdt1;
  String uniCdt2;
  String uniCdt3;
  String uniCdt4;
  double qteCdt1;
  double qteCdt2;
  double qteCdt3;
  double qteCdt4;
  String remIntf;
  String descr2F;
  String originInitials;
  String pdsVar;
  double pdsStd;
  double expPvgst;
  String origin;
  String originCod;
  double stock;
  String typArt;
  String art48H;
  String sanSto11;
  String sansDelai;
  String stoNgere;
  int menuItem;

  ProductModel({
    required this.codArt,
    required this.desArtf,
    required this.grpArt,
    required this.prices,
    required this.codUniPrice,
    required this.codUni,
    required this.uniCdt1,
    required this.uniCdt2,
    required this.uniCdt3,
    required this.uniCdt4,
    required this.qteCdt1,
    required this.qteCdt2,
    required this.qteCdt3,
    required this.qteCdt4,
    required this.remIntf,
    required this.descr2F,
    required this.originInitials,
    required this.pdsVar,
    required this.pdsStd,
    required this.expPvgst,
    required this.origin,
    required this.originCod,
    required this.stock,
    required this.typArt,
    required this.art48H,
    required this.sanSto11,
    required this.sansDelai,
    required this.stoNgere,
    required this.menuItem,
  });

  factory ProductModel.fromJson(Map<String, dynamic> json) => ProductModel(
    codArt: json["cod_art"],
    desArtf: json["des_artf"],
    grpArt: json["grp_art"],
    prices: json["prices"]?.toDouble(),
    codUniPrice: json["cod_uni_price"],
    codUni: json["cod_uni"],
    uniCdt1: json["uni_cdt1"],
    uniCdt2: json["uni_cdt2"],
    uniCdt3: json["uni_cdt3"],
    uniCdt4: json["uni_cdt4"],
    qteCdt1: json["qte_cdt1"],
    qteCdt2: json["qte_cdt2"],
    qteCdt3: json["qte_cdt3"],
    qteCdt4: json["qte_cdt4"],
    remIntf: json["rem_intf"],
    descr2F: json["descr2_f"],
    originInitials: json["origin_initials"],
    pdsVar: json["pds_var"],
    pdsStd: json["pds_std"],
    expPvgst: json["exp_pvgst"],
    origin: json["origin"],
    originCod: json["origin_cod"],
    stock: json["stock"],
    typArt: json["typ_art"],
    art48H: json["art_48h"],
    sanSto11: json["san_sto11"],
    sansDelai: json["sans_delai"],
    stoNgere: json["sto_ngere"],
    menuItem: json["menu_item"],
  );

  Map<String, dynamic> toJson() => {
    "cod_art": codArt,
    "des_artf": desArtf,
    "grp_art": grpArt,
    "prices": prices,
    "cod_uni_price": codUniPrice,
    "cod_uni": codUni,
    "uni_cdt1": uniCdt1,
    "uni_cdt2": uniCdt2,
    "uni_cdt3": uniCdt3,
    "uni_cdt4": uniCdt4,
    "qte_cdt1": qteCdt1,
    "qte_cdt2": qteCdt2,
    "qte_cdt3": qteCdt3,
    "qte_cdt4": qteCdt4,
    "rem_intf": remIntf,
    "descr2_f": descr2F,
    "origin_initials": originInitials,
    "pds_var": pdsVar,
    "pds_std": pdsStd,
    "exp_pvgst": expPvgst,
    "origin": origin,
    "origin_cod": originCod,
    "stock": stock,
    "typ_art": typArt,
    "art_48h": art48H,
    "san_sto11": sanSto11,
    "sans_delai": sansDelai,
    "sto_ngere": stoNgere,
    "menu_item": menuItem,
  };
}
